### ISSUE TITLE
perf: global state for vault properties

### ISSUE THREAD

**Issue by Luigy-Lemon** [gnosis/sdai-frontend#5]
Implement a global store similar to AccountStore for the vault data. This can be used to calculate the APY, live share value, etc offline. This store can be updated with a WebSocket subscription and should be used for:

Transaction overview (right now we're making RPC requests and the value flashes on change)
Live value
Vault APY
(w)xDAI -> sDAI conversion rate

**Comment by filoozom** [comment]
Implemented in adf35d05c1844cd9663df2d84a48f2521c6271e2 (except for the WebSocket subscription).
